name: BFF_Flutter_UI
description: A sample project to demo consuming a REST API through an OAuth2 BFF
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  http: ^1.1.0
  provider: ^6.1.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
