server:
  port: 8080
  ssl:
    enabled: false

scheme: http
issuer: https://oidc.c4-soft.com/auth/realms/master
client-id: spring-addons-confidential
client-secret: change-me
user-name-attribute: preferred_username
gateway-uri: ${scheme}://localhost:${server.port}
greetings-api-uri: ${scheme}://localhost:7084
ui-uri: ${scheme}://localhost:4200

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
            user-name-attribute: ${user-name-attribute}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
            - roles
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - SaveSession
      routes:
      # set a redirection from / to the UI
      - id: home
        uri: ${gateway-uri}
        predicates:
        - Path=/
        filters:
        - RedirectTo=301,${gateway-uri}/ui/
      # BFF access to greetings API (with TokenRelay replacing session cookies with access tokens)
      # To be used by SPAs (Angular app in our case)
      - id: greetings-api-bff
        uri: ${greetings-api-uri}
        predicates:
        - Path=/bff/v1/**
        filters:
        - TokenRelay=
        - StripPrefix=2
      - id: ui
        uri: ${ui-uri}
        predicates:
        - Path=/ui/**

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${issuer}
          authorities:
          - path: $.realm_access.roles
          username-claim: ${user-name-attribute}
        client:
          client-uri: ${gateway-uri}
          security-matchers: 
          - /login/**
          - /oauth2/**
          - /logout
          - /bff/**
          permit-all:
          - /login/**
          - /oauth2/**
          - /bff/**
          cors:
          - path: /bff/**
            allowed-origin-patterns:
            - ${gateway-uri}
            - https://localhost/
          csrf: cookie-accessible-from-js
          login-path: /ui/
          post-login-redirect-path: /ui/
          post-logout-redirect-path: /ui/
          oauth2-redirections:
            rp-initiated-logout: NO_CONTENT
        resourceserver:
          permit-all:
          - /
          - /login-options
          - /ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
          - /favicon.ico
          cors:
          - path: /login-options
            allowed-origin-patterns:
            - ${gateway-uri}
            - https://localhost/

logging:
  level:
    org:
      springframework:
        security: TRACE
        
---
spring:
  config:
    activate:
      on-profile: ssl

scheme: https
server:
  ssl:
    enabled: true
        
---
spring:
  config:
    activate:
      on-profile: mobile
com:
  c4-soft:
    springaddons:
      oidc:
        client:
          oauth2-redirections:
            pre-authorization-code: NO_CONTENT
            post-authorization-code: NO_CONTENT
            
# gateway-uri: ${scheme}://10.0.2.2:${server.port}