server:
  port: 7443
  ssl:
    enabled: false

scheme: http
keycloak-port: 8442
gateway-uri: ${scheme}://localhost:${server.port}
keycloak-issuer-uri: ${scheme}://localhost:${keycloak-port}/realms/master
users-api-uri: ${scheme}://localhost:6443/users
angular-uri: ${scheme}://localhost:4200

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-issuer-uri}
            user-name-attribute: preferred_username
        registration:
          spring-addons-confidential:
            provider: keycloak
            client-id: spring-addons-confidential
            client-secret: change-me
            authorization-grant-type: authorization_code
            scope: openid,profile,email

  cloud:
    gateway:
      default-filters:
      - TokenRelay=
      - RemoveRequestHeader=Cookie
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - SaveSession
      routes:
      - id: users
        uri: ${users-api-uri}
        predicates:
        - Path=/users/**
      - id: ui
        uri: ${angular-uri}
        predicates:
        - Path=/ui/**
      - id: home
        uri: ${angular-uri}
        predicates:
        - Path=/
        filters:
        - RewritePath=/,/ui

---
spring:
  config:
    activate:
      on-profile: ssl

server:
  ssl:
    enabled: true

scheme: https
keycloak-port: 8443