server:
  port: 6443
  ssl:
    enabled: false

com:
  c4-soft:
    springaddons:
      security:
        issuers:
          - location: http://localhost:8442/realms/master
            authorities:
              claims:
                - realm_access.roles
                - resource_access.spring-addons-confidential.roles
        cors:
          - path: /**
            allowed-origins: "*"
        permit-all: /v3/api-docs/**

---
spring:
  config:
    activate:
      on-profile: ssl

server:
  ssl:
    enabled: true
    
com:
  c4-soft:
    springaddons:
      security:
        issuers:
          - location: https://localhost:8443/realms/master
            authorities:
              claims:
                - realm_access.roles
                - resource_access.spring-addons-confidential.roles