server:
  ssl:
    enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

origins: http://localhost:4200
keycloak: http://localhost:8442/realms/master
cognito: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_RzhmgLwjl
auth0: https://dev-ch4mpy.eu.auth0.com/

com:
  c4-soft:
    springaddons:
      security:
        cors:
        - path: /**
          allowed-origins: ${origins}
        issuers:
        - location: ${keycloak}
          username-claim: preferred_username
          authorities:
            claims:
            - realm_access.roles
            - resource_access.spring-addons-public.role
            - resource_access.spring-addons-confidential.roles
        - location: ${cognito}
          username-claim: username
          authorities:
            claims: 
            - cognito:groups
        - location: ${auth0}
          username-claim: email
          authorities:
            claims: 
            - roles
            - permissions
        permit-all: 
        - "/actuator/health/readiness"
        - "/actuator/health/liveness"
        - "/v3/api-docs/**"
        
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

---
origins: https://localhost:4200
keycloak: https://localhost:8443/realms/master

server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl
